# Generated by Django 5.2.6 on 2025-10-13 04:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disallowedword',
            name='word',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='disallowedword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('word'), name='unique_lower_word'),
        ),
    ]
